### PR TITLE
Windows compile

### PR DESCRIPTION
**Pull request by haijieg**
Bootstrap the windows compile process
- Change mshadow and dmlc submodule to reference dato-code/*

### CODE REVIEW

**Comment by haijieg** [comment]
do NOT merge this yet, I'd like to test it on real windows build and squash the commits

**Comment by haijieg** [comment]
jenkins pls

**Comment by haijieg** [comment]
jenkins pls

**Comment by haijieg** [comment]
This PR is ready to merge. It contains the fixes here https://github.com/dato-code/mxnet/pull/12 to prevent python hanging on termination.

Please review @antinucleon

**Comment by antinucleon** [comment]
Let's rebase it then merge this?

**Pull request merged**
